# Fetch the position PID constants for the given node and motor

uint8 node 
uint8 channel
---
bool success
string error "success"
float32 p 
float32 i 
float32 d
float32 max_i
uint32 deadzone 
int32 max_pos 
int32 min_pos 